<?php

namespace OC\UserBundle\Repository;

/**
 * UsersCampaniesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UsersCampaniesRepository extends \Doctrine\ORM\EntityRepository
{
}
