# src/OC/PlatformBundle/Resources/config/routing.yml

oc_platform_home:
    path:      /hello
    defaults:
        _controller: PlatformBundle:Advert:index
    requirements:
        page: \d*

oc_platform_view:
    path:      /advert/{id}
    defaults:
        _controller: PlatformBundle:Advert:view
    requirements:
        id: \d+

oc_platform_add:
    path:      /add
    defaults:
        _controller: PlatformBundle:Advert:add

oc_platform_edit:
    path:      /edit/{id}
    defaults:
        _controller: PlatformBundle:Advert:edit
    requirements:
        id: \d+

oc_platform_delete:
    path:      /delete/{id}
    defaults:
        _controller: PlatformBundle:Advert:delete
    requirements:
        id: \d+

oc_platform_mobile:
    path:      /mobile
    defaults:
        _controller: PlatformBundle:Advert:mobile
