# src/OC/PlatformBundle/Resources/config/routing.yml

oc_platform_home:
    path:      /hello
    defaults:
        _controller: PlatformBundle:Advert:index
    requirements:
        page: \d*

oc_platform_view:
    path:      /advert/view
    defaults:
        _controller: PlatformBundle:Advert:view

oc_platform_viewad:
    path:      /advert/viewad/{id}
    defaults:
        _controller: PlatformBundle:Advert:viewad

oc_platform_script:
    path:      /script
    defaults:
        _controller: PlatformBundle:Advert:script
oc_platform_form:
    path:      /form
    defaults:
        _controller: PlatformBundle:Advert:form


oc_platform_add:
    path:      /add
    defaults:
        _controller: PlatformBundle:Advert:add

call:
    path:      /call
    defaults:
        _controller: PlatformBundle:Advert:call


oc_platform_edit:
    path:      /edit/{id}
    defaults:
        _controller: PlatformBundle:Advert:edit
    requirements:
        id: \d+

oc_platform_delete:
    path:      /delete/{id}
    defaults:
        _controller: PlatformBundle:Advert:delete
    requirements:
        id: \d+

oc_platform_mobile:
    path:      /mobile
    defaults:
        _controller: PlatformBundle:Advert:mobile
